{"uid":"27b8832a487c322f","name":"Create a new Category","fullName":"TestInventory.TestInventory#test_Add_newCategory_2___frugal_latido_com_np____Test_123____E___POM_for_Bottle__WebApp__TestData__InventoryData__Image__BikerJacket_jpg_____Automation__Item_01_____AT_IT01____This_is_from_an_automated_Script__01____0___Box__","historyId":"f891b16994da8b5198df4dbd51b73ec6","time":{"start":1685108483113,"stop":1685108500108,"duration":16995},"status":"failed","statusMessage":"AssertionError: None != True : Adding a New Category Failed","statusTrace":"self = <TestsCases.TestInventory.TestInventory testMethod=test_Add_newCategory_2___frugal_latido_com_np____Test_123____E___PO...yData__Image__BikerJacket_jpg_____Automation__Item_01_____AT_IT01____This_is_from_an_automated_Script__01____0___Box__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nImagePath = 'E:\\\\POM_for_Bottle\\\\WebApp\\\\TestData\\\\InventoryData\\\\Image\\\\BikerJacket.jpg'\nname = '(Automation) Item 01 ', code = 'AT-IT01'\ndesc = 'This is from an automated Script (01)', leather_flag = 0, unit = 'Box'\n\n    @allure.title(f\"Create a new Category\")\n    @allure.story(\"Create a new Category from Add button \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/InventoryData/InventoryTestCase.xlsx\", \"TestInventory\"))\n    @unpack\n    def test_Add_newCategory(self, username, password, ImagePath, name, code, desc, leather_flag, unit):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\n        # Checking if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\", attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestInventory.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestInventory.py:42: in test_Add_newCategory\n    self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: None != True : Adding a New Category Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: None != True : Adding a New Category Failed","statusTrace":"self = <TestsCases.TestInventory.TestInventory testMethod=test_Add_newCategory_2___frugal_latido_com_np____Test_123____E___PO...yData__Image__BikerJacket_jpg_____Automation__Item_01_____AT_IT01____This_is_from_an_automated_Script__01____0___Box__>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nImagePath = 'E:\\\\POM_for_Bottle\\\\WebApp\\\\TestData\\\\InventoryData\\\\Image\\\\BikerJacket.jpg'\nname = '(Automation) Item 01 ', code = 'AT-IT01'\ndesc = 'This is from an automated Script (01)', leather_flag = 0, unit = 'Box'\n\n    @allure.title(f\"Create a new Category\")\n    @allure.story(\"Create a new Category from Add button \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/InventoryData/InventoryTestCase.xlsx\", \"TestInventory\"))\n    @unpack\n    def test_Add_newCategory(self, username, password, ImagePath, name, code, desc, leather_flag, unit):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\n        # Checking if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\", attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestInventory.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestInventory.py:42: in test_Add_newCategory\n    self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: None != True : Adding a New Category Failed","steps":[],"attachments":[{"uid":"cd1a917458e73e45","name":"Failed_for_customer","source":"cd1a917458e73e45.png","type":"image/png","size":110197},{"uid":"aad7ab4a15feb8ec","name":"log","source":"aad7ab4a15feb8ec.txt","type":"text/plain","size":131}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":true,"stepsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"feature","value":"Inventory"},{"name":"severity","value":"normal"},{"name":"story","value":"Create a new Category from Add button "},{"name":"suite","value":"TestInventory"},{"name":"subSuite","value":"TestInventory"},{"name":"host","value":"0day"},{"name":"thread","value":"5116-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"TestInventory"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"27b8832a487c322f.json","parameterValues":[]}