{"uid":"d31a66edc466132b","name":"Create a new Order for existing Customer","fullName":"TestOrder.TestOrder#test_create_order_customer_3___frugal_latido_com_np____Test_123____9860838856____female____Lucha__male_____Mahogany_Antique____40____Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_","historyId":"1565d0f202ae29e0419b2df9b6f9e5e3","time":{"start":1687502220192,"stop":1687502289560,"duration":69368},"description":"Create an Order for existing Customer ","descriptionHtml":"<p>Create an Order for existing Customer</p>\n","status":"broken","statusMessage":"AttributeError: 'TestOrder' object has no attribute 'log'","statusTrace":"self = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\ncontactNo = '9860838856', gender = 'female', productname = 'Lucha (male)'\nleatherProfile = 'Mahogany Antique', leatherSize = '40', hardware = 'Silver'\nlining = 'Black', polyfill = 'No', size = '40', armhole = 5.6, height = 4.4\nshoulder = 5, weight = 46, length = 8, arms = 12, hips = 11, chest = 7\nwaist = 1, sleeves = 9, bodytype = 'General Fit', remark = 'Test 003'\ndate = '2023-06-29', OTP = 100900\n\n    @allure.title(f\"Create a new Order for existing Customer\")\n    @allure.description(\"Create an Order for existing Customer \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/OrderTestData/orderTestCase.xlsx\", \"forCustomer\"))\n    @unpack\n    def test_create_order_customer(self, username, password, contactNo, gender, productname, leatherProfile,\n                                   leatherSize, hardware, lining, polyfill, size, armhole, height, shoulder, weight,\n                                   length, arms, hips, chest, waist, sleeves, bodytype, remark, date, OTP):\n        self.LoginMethod.nativelogin(username, password)\n        test_case_name = f\"Create a new Order for existing Customer : {contactNo} \"\n        try:\n>           self.assertEqual(\n                self.Order.createOrder_Customer(contactNo, gender, productname, leatherProfile, leatherSize, hardware,\n                                                lining, polyfill, size, armhole, height, shoulder, weight, length, arms,\n                                                hips, chest, waist, sleeves, bodytype, remark, date, OTP),\n                \"Order Succesfully Created\", msg=\"Verification Failed to Create a new Order.\")\n\nTestOrder.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = 'Verification Failed to Create a new Order.'\n\n    def _patched_equals(self, first, second, msg=None):\n        try:\n>           old(self, first, second, msg)\n\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = 'Verification Failed to Create a new Order.'\n\n    def assertEqual(self, first, second, msg=None):\n        \"\"\"Fail if the two objects are unequal as determined by the '=='\n           operator.\n        \"\"\"\n        assertion_func = self._getAssertEqualityFunc(first, second)\n>       assertion_func(first, second, msg=msg)\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:845: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = \"None != 'Order Succesfully Created' : Verification Failed to Create a new Order.\"\n\n    def _baseAssertEqual(self, first, second, msg=None):\n        \"\"\"The default assertEqual implementation, not type specific.\"\"\"\n        if not first == second:\n            standardMsg = '%s != %s' % _common_shorten_repr(first, second)\n            msg = self._formatMessage(msg, standardMsg)\n>           raise self.failureException(msg)\nE           AssertionError: None != 'Order Succesfully Created' : Verification Failed to Create a new Order.\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:838: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\ncontactNo = '9860838856', gender = 'female', productname = 'Lucha (male)'\nleatherProfile = 'Mahogany Antique', leatherSize = '40', hardware = 'Silver'\nlining = 'Black', polyfill = 'No', size = '40', armhole = 5.6, height = 4.4\nshoulder = 5, weight = 46, length = 8, arms = 12, hips = 11, chest = 7\nwaist = 1, sleeves = 9, bodytype = 'General Fit', remark = 'Test 003'\ndate = '2023-06-29', OTP = 100900\n\n    @allure.title(f\"Create a new Order for existing Customer\")\n    @allure.description(\"Create an Order for existing Customer \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/OrderTestData/orderTestCase.xlsx\", \"forCustomer\"))\n    @unpack\n    def test_create_order_customer(self, username, password, contactNo, gender, productname, leatherProfile,\n                                   leatherSize, hardware, lining, polyfill, size, armhole, height, shoulder, weight,\n                                   length, arms, hips, chest, waist, sleeves, bodytype, remark, date, OTP):\n        self.LoginMethod.nativelogin(username, password)\n        test_case_name = f\"Create a new Order for existing Customer : {contactNo} \"\n        try:\n            self.assertEqual(\n                self.Order.createOrder_Customer(contactNo, gender, productname, leatherProfile, leatherSize, hardware,\n                                                lining, polyfill, size, armhole, height, shoulder, weight, length, arms,\n                                                hips, chest, waist, sleeves, bodytype, remark, date, OTP),\n                \"Order Succesfully Created\", msg=\"Verification Failed to Create a new Order.\")\n    \n        # Checking if assertion failed\n        except (NoSuchElementException, AssertionError, TimeoutException, AttributeError) as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\",\n                          attachment_type=AttachmentType.PNG)\n>           self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\nE           AttributeError: 'TestOrder' object has no attribute 'log'\n\nTestOrder.py:53: AttributeError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_TestOrder","time":{"start":1687500628072,"stop":1687500628072,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"hasContent":false}],"testStage":{"description":"Create an Order for existing Customer ","status":"broken","statusMessage":"AttributeError: 'TestOrder' object has no attribute 'log'","statusTrace":"self = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\ncontactNo = '9860838856', gender = 'female', productname = 'Lucha (male)'\nleatherProfile = 'Mahogany Antique', leatherSize = '40', hardware = 'Silver'\nlining = 'Black', polyfill = 'No', size = '40', armhole = 5.6, height = 4.4\nshoulder = 5, weight = 46, length = 8, arms = 12, hips = 11, chest = 7\nwaist = 1, sleeves = 9, bodytype = 'General Fit', remark = 'Test 003'\ndate = '2023-06-29', OTP = 100900\n\n    @allure.title(f\"Create a new Order for existing Customer\")\n    @allure.description(\"Create an Order for existing Customer \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/OrderTestData/orderTestCase.xlsx\", \"forCustomer\"))\n    @unpack\n    def test_create_order_customer(self, username, password, contactNo, gender, productname, leatherProfile,\n                                   leatherSize, hardware, lining, polyfill, size, armhole, height, shoulder, weight,\n                                   length, arms, hips, chest, waist, sleeves, bodytype, remark, date, OTP):\n        self.LoginMethod.nativelogin(username, password)\n        test_case_name = f\"Create a new Order for existing Customer : {contactNo} \"\n        try:\n>           self.assertEqual(\n                self.Order.createOrder_Customer(contactNo, gender, productname, leatherProfile, leatherSize, hardware,\n                                                lining, polyfill, size, armhole, height, shoulder, weight, length, arms,\n                                                hips, chest, waist, sleeves, bodytype, remark, date, OTP),\n                \"Order Succesfully Created\", msg=\"Verification Failed to Create a new Order.\")\n\nTestOrder.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = 'Verification Failed to Create a new Order.'\n\n    def _patched_equals(self, first, second, msg=None):\n        try:\n>           old(self, first, second, msg)\n\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = 'Verification Failed to Create a new Order.'\n\n    def assertEqual(self, first, second, msg=None):\n        \"\"\"Fail if the two objects are unequal as determined by the '=='\n           operator.\n        \"\"\"\n        assertion_func = self._getAssertEqualityFunc(first, second)\n>       assertion_func(first, second, msg=msg)\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:845: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nfirst = None, second = 'Order Succesfully Created'\nmsg = \"None != 'Order Succesfully Created' : Verification Failed to Create a new Order.\"\n\n    def _baseAssertEqual(self, first, second, msg=None):\n        \"\"\"The default assertEqual implementation, not type specific.\"\"\"\n        if not first == second:\n            standardMsg = '%s != %s' % _common_shorten_repr(first, second)\n            msg = self._formatMessage(msg, standardMsg)\n>           raise self.failureException(msg)\nE           AssertionError: None != 'Order Succesfully Created' : Verification Failed to Create a new Order.\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python310\\lib\\unittest\\case.py:838: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestsCases.TestOrder.TestOrder testMethod=test_create_order_customer_3___frugal_latido_com_np____Test_123____98608388...___Silver____Black____No____40___5_6__4_4__5__46__8__12__11__7__1__9___General_Fit____Test_003____2023_06_29___100900_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\ncontactNo = '9860838856', gender = 'female', productname = 'Lucha (male)'\nleatherProfile = 'Mahogany Antique', leatherSize = '40', hardware = 'Silver'\nlining = 'Black', polyfill = 'No', size = '40', armhole = 5.6, height = 4.4\nshoulder = 5, weight = 46, length = 8, arms = 12, hips = 11, chest = 7\nwaist = 1, sleeves = 9, bodytype = 'General Fit', remark = 'Test 003'\ndate = '2023-06-29', OTP = 100900\n\n    @allure.title(f\"Create a new Order for existing Customer\")\n    @allure.description(\"Create an Order for existing Customer \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/OrderTestData/orderTestCase.xlsx\", \"forCustomer\"))\n    @unpack\n    def test_create_order_customer(self, username, password, contactNo, gender, productname, leatherProfile,\n                                   leatherSize, hardware, lining, polyfill, size, armhole, height, shoulder, weight,\n                                   length, arms, hips, chest, waist, sleeves, bodytype, remark, date, OTP):\n        self.LoginMethod.nativelogin(username, password)\n        test_case_name = f\"Create a new Order for existing Customer : {contactNo} \"\n        try:\n            self.assertEqual(\n                self.Order.createOrder_Customer(contactNo, gender, productname, leatherProfile, leatherSize, hardware,\n                                                lining, polyfill, size, armhole, height, shoulder, weight, length, arms,\n                                                hips, chest, waist, sleeves, bodytype, remark, date, OTP),\n                \"Order Succesfully Created\", msg=\"Verification Failed to Create a new Order.\")\n    \n        # Checking if assertion failed\n        except (NoSuchElementException, AssertionError, TimeoutException, AttributeError) as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\",\n                          attachment_type=AttachmentType.PNG)\n>           self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\nE           AttributeError: 'TestOrder' object has no attribute 'log'\n\nTestOrder.py:53: AttributeError","steps":[],"attachments":[{"uid":"bbdcee5eba92f40d","name":"Failed_for_customer","source":"bbdcee5eba92f40d.png","type":"image/png","size":125801},{"uid":"627a1cf336d29359","name":"log","source":"627a1cf336d29359.txt","type":"text/plain","size":3308}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":true,"stepsCount":0,"hasContent":true},"afterStages":[{"name":"_unittest_setUpClass_fixture_TestOrder::0","time":{"start":1687502716177,"stop":1687502716177,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Order List"},{"name":"severity","value":"normal"},{"name":"suite","value":"TestOrder"},{"name":"subSuite","value":"TestOrder"},{"name":"host","value":"0day"},{"name":"thread","value":"2692-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"TestOrder"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":3,"unknown":0,"total":4},"items":[{"uid":"df85ef6a82a55ec0","status":"passed","time":{"start":1686891653187,"stop":1686891712644,"duration":59457}},{"uid":"7f0f7e9c1d3318e","status":"passed","time":{"start":1686288703157,"stop":1686288766632,"duration":63475}},{"uid":"1cc75f5c5fa90c1d","status":"passed","time":{"start":1685710668121,"stop":1685710724335,"duration":56214}}]},"tags":[]},"source":"d31a66edc466132b.json","parameterValues":[]}